name: Build Python Wheels
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12]
    runs-on: ${{ matrix.os }}
    env:
      SYSTEM_VERSION_COMPAT: 0 # https://github.com/actions/setup-python/issues/469#issuecomment-1192522949
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install build
    - name: Build package
      run: python -m build
    - name: Test
      run: |
        pip install dist/*.whl
        python -m unittest
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/*.whl